export const KEYWORD_TO_KOREAN: Record<string, string> = {
    // Positive Traits
    'Creative': '창의적인',
    'Funny': '재미있는',
    'Kind': '친절한',
    'Energetic': '활기찬',
    'Thoughtful': '사려 깊은',
    'Organized': '체계적인',
    'Adventurous': '모험적인',
    'Loyal': '의리 있는',
    'Confident': '자신감 있는',
    'Empathetic': '공감 능력이 좋은',
    'Ambitious': '야심 있는',
    'Calm': '침착한',
    'Spontaneous': '즉흥적인',
    'Patient': '인내심 있는',
    'Optimistic': '낙천적인',
    'Analytical': '분석적인',
    'Curious': '호기심 많은',
    'Reliable': '신뢰할 수 있는',
    'Friendly': '우호적인',
    'Independent': '독립적인',
    'Passionate': '열정적인',
    'Honest': '솔직한',
    'Humble': '겸손한',
    'Charming': '매력적인',
    'Wise': '지혜로운',
    'Diligent': '성실한',
    'Generous': '관대한',
    'Charismatic': '카리스마 있는',
    'Romantic': '로맨틱한',
    'Resilient': '회복탄력성 좋은',

    // Bold Personality
    'Stubborn': '고집 센',
    'Impulsive': '충동적인',
    'Overthinking': '과하게 생각하는',
    'Moody': '기분 기복 있는',
    'Blunt': '직설적인',
    'Perfectionist': '완벽주의',
    'Competitive': '승부욕 강한',
    'People-pleaser': '눈치 많이 보는',
    'Sarcastic': '비꼬는',
    'Forgetful': '잘 까먹는',
    'Talkative': '수다스러운',
    'Dramatic': '드라마틱한',
    'Expressive': '감정 표현이 풍부한',
    'Opinionated': '주관 뚜렷한',
    'Loud': '목소리 큰',
    'Quiet': '조용한',
    'Serious': '진지한',
    'Playful': '장난기 많은',
    'Eccentric': '4차원',
    'Intense': '강렬한',
    'Chill': '쿨한',
    'High-maintenance': '손이 많이 가는',
    'Low-maintenance': '털털한',
    'Risk-taker': '모험을 즐기는',
    'Cautious': '신중한',
    'Direct': '돌직구 던지는',
    'Persuasive': '설득력 있는',
    'Unpredictable': '예측불가',
    'Trendy': '트렌디한',
    'Critical': '비판적인',
    'Bossy': '대장질하는',

    // Inner Self
    'Lazy': '게으른',
    'Procrastinator': '미루는 습관 있는',
    'Messy': '정리 못하는',
    'Sensitive': '상처 잘 받는',
    'Shy': '수줍음 많은',
    'Secretive': '속마음 잘 숨기는',
    'Rebellious': '반항적인',
    'Emotional': '감수성 풍부한',
    'Introverted': '내향적인 (I)',
    'Extroverted': '외향적인 (E)',
    'Anxious': '걱정 많은',
    'Dreamer': '몽상가',
    'Realist': '현실주의자',
    'Lonely': '외로움 타는',
    'Needy': '애정결핍',
    'Complex': '생각이 복잡한',
    'Simple': '단순한',
    'Innocent': '순수한',
    'Mature': '어른스러운',
    'Childish': '애 같은',
    'Sentimental': '감상적인',
    'Obsessive': '집착하는',
    'Indecisive': '결정장애 있는',
    'Easily-bored': '금방 질리는',
    'Workaholic': '워커홀릭',
    'Homebody': '집순이/집돌이',
    'Social-butterfly': '인싸/마당발',
    'Skeptical': '의심 많은',
    'Gullible': '팔랑귀',
    'Nostalgic': '추억에 젖는',

    // Vibes
    'Night-owl': '야행성',
    'Clumsy': '허당',
    'Chaotic': '혼돈형 인간',
    'Free-spirited': '자유로운 영혼',
    'Weirdly-lucky': '이상하게 운 좋은',
    'Coffee-dependent': '카페인 의존',
    'Late': '지각 자주 하는',
    'Always-hungry': '항상 배고픈',
    'Over-apologetic': '쓸데없이 사과하는',
    'Golden-retriever-energy': '골든리트리버 재질',
    'Sociable': '사람 좋아하는',
    'Black-cat-energy': '블랙캣 재질',
    'Chic': '시크한',
    'Early-bird': '아침형 인간',
    'Fashionista': '패셔니스타',
    'Minimalist': '미니멀리스트',
    'Maximalist': '맥시멀리스트',
    'Tech-savvy': '얼리어답터',
    'Analogue-soul': '아날로그 감성',
    'Foodie': '맛잘알',
    'Gamer': '겜돌이/겜순이',
    'Party-animal': '파티광',
    'Nature-lover': '자연인',
    'City-slicker': '도시 사람',
    'Idol-fan': '아이돌 덕후',
    'Geek': '너드미',
    'Gym-rat': '헬창',
    'Bookworm': '독서광',
    'Movie-buff': '영화광',
    'Playlist-curator': '플리에 진심인',
    'Meme-lord': '짤 부자',
    'Photogenic': '사진빨 잘 받는',
    'Hipster': '힙스터',
    'Stylish': '스타일리시한',
};

export const getKoreanKeyword = (key: string): string => {
    return KEYWORD_TO_KOREAN[key] || key;
};
